public class HelloWorld {
    
    // Variables 
    
    // Methods
    // Access Modifier (Pirivate, Public, Protected)
    public void Sayhi(string strname) // parameter 1: Name
    {
        System.debug('Hi there i m a method in  hello world class !!'); // APEX does not have print function to show something on the screen
    	System.debug('Welcome :' + strname);
    
    }
    
    public static void GetCurrentTime()
    {
        System.debug('Current Time is::');
    }
    
    // Access Modifiers 
    
    
   	// Annotations	

}